device: cuda
link_length: [2,2]
link_mass: [1.0,1.0]
gravity: 9.81
total_energy: 90

# source_point (goal)
q_s: [-0.5,0.8]

# for visualization
nbDim: 200
subsampling: [10,10]
uniformTips: [6,6]


# for backtracking
nbPoints: 1000
step_size: 0.1

# circle obstacle
circle_center: [0.0,0.0]
circle_radius: 0.8
